# COVID-19 Pandemic Trend Analysis and Interactive Dashboard

## Module 1: Data Collection & Understanding

### Objectives
- Load the COVID-19 dataset.
- Understand the dataset structure.
- Explore columns and data types.
- Identify missing values.
- Prepare the dataset for preprocessing.

**Dataset Source:** Our World in Data (OWID)

In [3]:
# Import required libraries

import pandas as pd
import numpy as np

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

print("Libraries imported successfully!")

Libraries imported successfully!

In [4]:
# Load the dataset

import pandas as pd

file_path = "../data/owid-covid-data.csv"

df = pd.read_csv(file_path)

print("✅ Dataset loaded successfully!")

✅ Dataset loaded successfully!

In [6]:
# Dataset Shape

print("Rows   :", df.shape[0])
print("Columns:", df.shape[1])

Rows   : 350085
Columns: 67

In [7]:
# Dataset Information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 350085 entries, 0 to 350084
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    350085 non-null  object
 1   continent                                   333420 non-null  object
 2   location                                    350085 non-null  object
 3   date                                        350085 non-null  object
 4   total_cases                                 312088 non-null  float64
 5   new_cases                                   340457 non-null  float64
 6   new_cases_smoothed                          339198 non-null  float64
 7   total_deaths                                290501 non-null  float64
 8   new_deaths                                  340511 non-null  float64
 9   new_deaths_smoothed                         339281 non-null  float64
 10  total_cases_per_million                     312088 non-null  float64
 11  new_cases_per_million                       340457 non-null  float64
 12  new_cases_smoothed_per_million              339198 non-null  float64
 13  total_deaths_per_million                    290501 non-null  float64
 14  new_deaths_per_million                      340511 non-null  float64
 15  new_deaths_smoothed_per_million             339281 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                37615 non-null   float64
 18  icu_patients_per_million                    37615 non-null   float64
 19  hosp_patients                               38902 non-null   float64
 20  hosp_patients_per_million                   38902 non-null   float64
 21  weekly_icu_admissions                       10205 non-null   float64
 22  weekly_icu_admissions_per_million           10205 non-null   float64
 23  weekly_hosp_admissions                      23253 non-null   float64
 24  weekly_hosp_admissions_per_million          23253 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          79308 non-null   float64
 35  people_vaccinated                           75911 non-null   float64
 36  people_fully_vaccinated                     72575 non-null   float64
 37  total_boosters                              47562 non-null   float64
 38  new_vaccinations                            65346 non-null   float64
 39  new_vaccinations_smoothed                   180718 non-null  float64
 40  total_vaccinations_per_hundred              79308 non-null   float64
 41  people_vaccinated_per_hundred               75911 non-null   float64
 42  people_fully_vaccinated_per_hundred         72575 non-null   float64
 43  total_boosters_per_hundred                  47562 non-null   float64
 44  new_vaccinations_smoothed_per_million       180718 non-null  float64
 45  new_people_vaccinated_smoothed              180489 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  180489 non-null  float64
 47  stringency_index                            197651 non-null  float64
 48  population_density                          297178 non-null  float64
 49  median_age                                  276367 non-null  float64
 50  aged_65_older                               266708 non-null  float64
 51  aged_70_older                               273597 non-null  float64
 52  gdp_per_capita                              270863 non-null  float64
 53  extreme_poverty                             174561 non-null  float64
 54  cardiovasc_death_rate                       271487 non-null  float64
 55  diabetes_prevalence                         285303 non-null  float64
 56  female_smokers                              203659 non-null  float64
 57  male_smokers                                200889 non-null  float64
 58  handwashing_facilities                      132973 non-null  float64
 59  hospital_beds_per_thousand                  239669 non-null  float64
 60  life_expectancy                             322072 non-null  float64
 61  human_development_index                     263138 non-null  float64
 62  population                                  350085 non-null  float64
 63  excess_mortality_cumulative_absolute        12184 non-null   float64
 64  excess_mortality_cumulative                 12184 non-null   float64
 65  excess_mortality                            12184 non-null   float64
 66  excess_mortality_cumulative_per_million     12184 non-null   float64
dtypes: float64(62), object(5)
memory usage: 179.0+ MB

In [8]:
# Missing Values

missing_values = (
    df.isnull()
      .sum()
      .sort_values(ascending=False)
      .to_frame(name="Missing Values")
)

missing_values["Percentage"] = (
    missing_values["Missing Values"] / len(df) * 100
).round(2)

missing_values.head(20)

                                      Missing Values  Percentage
weekly_icu_admissions                         339880       97.08
weekly_icu_admissions_per_million             339880       97.08
excess_mortality                              337901       96.52
excess_mortality_cumulative_absolute          337901       96.52
excess_mortality_cumulative                   337901       96.52
...                                              ...         ...
people_fully_vaccinated_per_hundred           277510       79.27
people_fully_vaccinated                       277510       79.27
new_tests                                     274682       78.46
new_tests_per_thousand                        274682       78.46
people_vaccinated_per_hundred                 274174       78.32

[20 rows x 2 columns]

In [9]:
# Statistical Summary

df.describe().T

,count,mean,std,min,25%,50%,75%,max
total_cases,312088.0,6.683354e+06,4.068903e+07,1.0000,8090.000000,7.020500e+04,7.409558e+05,7.714071e+08
new_cases,340457.0,9.601634e+03,1.102769e+05,0.0000,0.000000,2.000000e+00,2.640000e+02,8.401961e+06
new_cases_smoothed,339198.0,9.637066e+03,9.447784e+04,0.0000,0.286000,2.485700e+01,4.978570e+02,6.402036e+06
total_deaths,290501.0,8.602180e+04,4.398873e+05,1.0000,127.000000,1.328000e+03,1.192200e+04,6.972139e+06
new_deaths,340511.0,8.551106e+01,6.136880e+02,0.0000,0.000000,0.000000e+00,3.000000e+00,2.793900e+04
...,...,...,...,...,...,...,...,...
population,350085.0,1.284633e+08,6.607694e+08,47.0000,449002.000000,5.882259e+06,2.830170e+07,7.975105e+09
excess_mortality_cumulative_absolute,12184.0,5.281637e+04,1.492195e+05,-37726.0980,120.225025,5.885850e+03,3.742344e+04,1.289776e+06
excess_mortality_cumulative,12184.0,9.738648e+00,1.230444e+01,-44.2300,1.400000,8.075000e+00,1.536000e+01,7.662000e+01
excess_mortality,12184.0,1.134526e+01,2.518130e+01,-95.9200,-1.600000,5.720000e+00,1.630250e+01,3.776300e+02
excess_mortality_cumulative_per_million,12184.0,1.669026e+03,1.938556e+03,-2752.9248,72.395046,1.105405e+03,2.740130e+03,1.029292e+04

In [10]:
# Random Sample

df.sample(5, random_state=42)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million,total_tests,new_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,positive_rate,tests_per_case,tests_units,total_vaccinations,people_vaccinated,people_fully_vaccinated,total_boosters,new_vaccinations,new_vaccinations_smoothed,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,total_boosters_per_hundred,new_vaccinations_smoothed_per_million,new_people_vaccinated_smoothed,new_people_vaccinated_smoothed_per_hundred,stringency_index,population_density,median_age,aged_65_older,aged_70_older,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
100762,FRO,Europe,Faeroe Islands,2022-12-25,34658.0,0.0,0.000,28.0,0.0,0.000,652484.139,0.000,0.000,527.138,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.11,35.308,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,80.67,NaN,53117.0,NaN,NaN,NaN,NaN
107827,GUF,South America,French Guiana,2023-05-14,98041.0,0.0,0.000,413.0,0.0,0.000,321901.841,0.000,0.000,1356.019,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.3,NaN,2.897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,79.95,NaN,304568.0,256.39996,7.09,-41.75,821.3709
129369,GNB,Africa,Guinea-Bissau,2021-08-30,5766.0,0.0,35.429,117.0,0.0,2.000,2738.438,0.000,16.826,55.567,0.000,0.950,0.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2088.0,NaN,NaN,NaN,NaN,992.0,1937.0,0.092,NaN,66.191,19.4,3.002,1.565,1548.675,67.1,382.474,2.42,NaN,NaN,6.403,NaN,58.32,0.480,2105580.0,NaN,NaN,NaN,NaN
114951,GHA,Africa,Ghana,2020-02-13,NaN,0.0,0.000,NaN,0.0,0.000,NaN,0.000,0.000,NaN,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.78,126.719,21.1,3.385,1.948,4227.630,12.0,298.245,4.97,0.3,7.7,41.047,0.9,64.07,0.611,33475870.0,NaN,NaN,NaN,NaN
224039,OWID_NAM,NaN,North America,2020-12-11,18203634.0,247938.0,230856.143,463299.0,4247.0,3275.857,30323.033,413.007,384.553,771.749,7.075,5.457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600323657.0,NaN,NaN,NaN,NaN

Module 2 – Data Cleaning & Preprocessing

Instead of deleting everything with missing values (which many projects do), we'll follow a production-ready strategy.

In [11]:
# Check duplicate rows

print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [12]:
# Convert date column into datetime format

df["date"] = pd.to_datetime(df["date"])

print(df["date"].dtype)

datetime64[ns]

In [13]:
missing = (
    df.isnull()
      .mean()
      .mul(100)
      .sort_values(ascending=False)
)

missing.head(20)

weekly_icu_admissions                   97.084994
weekly_icu_admissions_per_million       97.084994
excess_mortality                        96.519702
excess_mortality_cumulative_absolute    96.519702
excess_mortality_cumulative             96.519702
                                          ...
people_fully_vaccinated_per_hundred     79.269320
people_fully_vaccinated                 79.269320
new_tests                               78.461516
new_tests_per_thousand                  78.461516
people_vaccinated_per_hundred           78.316409
Length: 20, dtype: float64

In [14]:
# Columns having more than 90% missing values

high_missing = missing[missing > 90]

high_missing

weekly_icu_admissions                      97.084994
weekly_icu_admissions_per_million          97.084994
excess_mortality                           96.519702
excess_mortality_cumulative_absolute       96.519702
excess_mortality_cumulative                96.519702
excess_mortality_cumulative_per_million    96.519702
weekly_hosp_admissions                     93.357899
weekly_hosp_admissions_per_million         93.357899
dtype: float64

In [15]:
# Drop columns having more than 90% missing values

df = df.drop(columns=high_missing.index)

print("Remaining Columns:", df.shape[1])

Remaining Columns: 59

In [16]:
# Verify removed columns

set(high_missing.index).intersection(df.columns)

set()

In [17]:
print(df.shape)

(350085, 59)

In [18]:
# Check country-date structure

print("Countries:", df["location"].nunique())
print("Date range:", df["date"].min(), "to", df["date"].max())

print("\nDuplicate country-date combinations:")
print(df.duplicated(subset=["location", "date"]).sum())

Countries: 255
Date range: 2020-01-01 00:00:00 to 2023-10-24 00:00:00

Duplicate country-date combinations:
0

In [19]:
# Sort data by country and date

df = df.sort_values(
    by=["location", "date"]
).reset_index(drop=True)

print(df[["location", "date"]].head(10))

      location       date
0  Afghanistan 2020-01-03
1  Afghanistan 2020-01-04
2  Afghanistan 2020-01-05
3  Afghanistan 2020-01-06
4  Afghanistan 2020-01-07
5  Afghanistan 2020-01-08
6  Afghanistan 2020-01-09
7  Afghanistan 2020-01-10
8  Afghanistan 2020-01-11
9  Afghanistan 2020-01-12

In [20]:
# Check missing values in key analysis variables

key_columns = [
    "total_cases",
    "new_cases",
    "total_deaths",
    "new_deaths",
    "total_tests",
    "new_tests",
    "total_vaccinations",
    "new_vaccinations",
    "people_fully_vaccinated"
]

missing_key = df[key_columns].isna().sum().sort_values(ascending=False)

print(missing_key)

new_vaccinations           284739
people_fully_vaccinated    277510
new_tests                  274682
total_vaccinations         270777
total_tests                270698
total_deaths                59584
total_cases                 37997
new_cases                    9628
new_deaths                   9574
dtype: int64

In [21]:
# Missing percentage for key variables

missing_key_pct = (
    df[key_columns]
    .isna()
    .mean()
    .mul(100)
    .sort_values(ascending=False)
    .round(2)
)

print(missing_key_pct)

new_vaccinations           81.33
people_fully_vaccinated    79.27
new_tests                  78.46
total_vaccinations         77.35
total_tests                77.32
total_deaths               17.02
total_cases                10.85
new_cases                   2.75
new_deaths                  2.73
dtype: float64

In [22]:
# Fill missing case and death values with 0

case_death_columns = [
    "total_cases",
    "new_cases",
    "total_deaths",
    "new_deaths"
]

df[case_death_columns] = df[case_death_columns].fillna(0)

print("Missing values after filling:")
print(df[case_death_columns].isna().sum())

Missing values after filling:
total_cases     0
new_cases       0
total_deaths    0
new_deaths      0
dtype: int64